[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/bank"
  status = 301

[[redirects]]
  from = "/bank"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/bank/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/logic-final"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/logic-final/*"
  to = "/index.html"
  status = 200
